### ISSUE TITLE
After update to 1.20.0 kiota my body instead of json is binary data in request

### ISSUE THREAD

**Issue by illunix** [microsoft/kiota-typescript#1497] opened 2024-11-21 13:49 UTC
Hello, after update to 1.20.0 kiota, I've tried to test things out and it seems that request that always was sending json body right now is sending something like binary data?

![Image](https://github.com/user-attachments/assets/242c6dfd-193a-422a-a90f-060c06c8b8d0)

Packages versions that I use
```
        "@microsoft/kiota-abstractions": "1.0.0-preview.76",
        "@microsoft/kiota-bundle": "1.0.0-preview.76",
        "@microsoft/kiota-http-fetchlibrary": "1.0.0-preview.76",
        "@microsoft/kiota-serialization-form": "1.0.0-preview.76",
        "@microsoft/kiota-serialization-json": "1.0.0-preview.76",
        "@microsoft/kiota-serialization-multipart": "1.0.0-preview.76",
        "@microsoft/kiota-serialization-text": "1.0.0-preview.76",
```

Generated request
```ts
export interface SignInRequestBuilder extends BaseRequestBuilder<SignInRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ValidatedResultJsonWebToken>}
     * @throws {ValidatedResult} error when the service returns a 400 status code
     */
     post(body: SignInDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ValidatedResultJsonWebToken | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: SignInDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SignInRequestBuilderUriTemplate = "{+baseurl}/v1/auth/sign-in";
/**
 * Metadata for all the requests in the request builder.
 */
export const SignInRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: SignInRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        errorMappings: {
            400: createValidatedResultFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createValidatedResultJsonWebTokenFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSignInDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
```

**Comment by baywet** [comment] 2024-11-21 14:33
Closing as duplicate of #1439

**Closed by baywet** 2024-11-21 14:33 UTC
